# Generated by Django 6.1.1 on 2026-10-02 11:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionAuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('agent_name', models.CharField(default='Agent', max_length=64)),
                ('action_type', models.CharField(db_index=True, max_length=64)),
                ('target', models.TextField(blank=True, default='')),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='SUCCESS', max_length=24)),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('duration_ms', models.IntegerField(default=0)),
                ('executed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Execution Audit Log',
                'verbose_name_plural': 'Execution Audit Logs',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('agent_name', models.CharField(default='Agent', max_length=64)),
                ('action_type', models.CharField(max_length=64)),
                ('command_text', models.TextField()),
                ('reason', models.TextField(blank=True, default='')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low (Read-Only / Safe)'), ('MEDIUM', 'Medium (Local Modification)'), ('HIGH', 'High (Terminal / System Execution)'), ('CRITICAL', 'Critical (High-Impact / Destructive)')], default='MEDIUM', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending User Action'), ('APPROVED', 'Approved by User'), ('DENIED', 'Denied by User'), ('TIMEOUT', 'Timed Out'), ('BLOCKED_POLICY', 'Blocked by Safety Policy')], db_index=True, default='PENDING', max_length=24)),
                ('decision', models.CharField(blank=True, choices=[('ALLOW_ONCE', 'Allow Once'), ('ALLOW_TASK', 'Allow for Entire Task'), ('DENY', 'Deny'), ('AUTO_BLOCKED', 'Automatically Blocked')], max_length=24, null=True)),
                ('timeout_seconds', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Permission Request',
                'verbose_name_plural': 'Permission Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyPolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('rule_type', models.CharField(choices=[('REGEX_BLOCK', 'Regex Block Pattern'), ('DOMAIN_WHITELIST', 'Allowed Domain Whitelist'), ('PATH_RESTRICTION', 'Restricted File Path'), ('COMMAND_WHITELIST', 'Pre-Approved Command')], default='REGEX_BLOCK', max_length=32)),
                ('pattern', models.CharField(max_length=512)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low (Read-Only / Safe)'), ('MEDIUM', 'Medium (Local Modification)'), ('HIGH', 'High (Terminal / System Execution)'), ('CRITICAL', 'Critical (High-Impact / Destructive)')], default='CRITICAL', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Safety Policy Rule',
                'verbose_name_plural': 'Safety Policy Rules',
                'ordering': ['name'],
            },
        ),
    ]
