# Generated by Django 6.1.1 on 2026-10-02 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileCompanionDevice',
            fields=[
                ('device_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('device_name', models.CharField(default='Mobile Companion', max_length=128)),
                ('device_type', models.CharField(default='android', max_length=32)),
                ('auth_token', models.CharField(db_index=True, max_length=256, unique=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('is_paired', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('permissions_allowed', models.JSONField(blank=True, default=list)),
                ('last_heartbeat', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Mobile Companion Device',
                'verbose_name_plural': 'Mobile Companion Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobilePairingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('pairing_secret', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
