# Generated by Django 6.1.1 on 2026-10-02 17:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_core', '0002_mobilecompaniondevice_mobilepairingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkstationMemory',
            fields=[
                ('memory_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(db_index=True, default='media', max_length=64)),
                ('window_title', models.CharField(blank=True, default='', max_length=512)),
                ('target_url', models.TextField(blank=True, default='')),
                ('app_name', models.CharField(blank=True, default='', max_length=128)),
                ('action_type', models.CharField(default='play_media', max_length=64)),
                ('content_snippet', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Workstation Memory',
                'verbose_name_plural': 'User Workstation Memories',
                'ordering': ['-created_at'],
            },
        ),
    ]
